import {
  BookOpen,
  Bus,
  ClipboardList,
  DollarSign,
  FileText,
  GraduationCap,
  Leaf,
  TrendingUp,
  UserPlus,
  UtensilsCrossed,
} from 'lucide-react'

import type { TransparenciaTabConfig } from './types'

export const transparenciaTabs: TransparenciaTabConfig[] = [
  {
    id: 'agricultura',
    label: 'Agricultura Familiar',
    icon: Leaf,
    colorClass: 'text-emerald-600',
    description: 'Compras locais, fornecedores e meta minima do PNAE.',
    supportText: 'PNAE e fornecedores',
  },
  {
    id: 'alimentacao',
    label: 'Alimentacao Escolar',
    icon: UtensilsCrossed,
    colorClass: 'text-orange-600',
    description: 'Refeicoes servidas, fontes dos alimentos e investimentos.',
    supportText: 'Refeicoes e investimento',
  },
  {
    id: 'cardapio',
    label: 'Cardapio',
    icon: ClipboardList,
    colorClass: 'text-pink-600',
    description: 'Planejamento semanal das refeicoes por escola e faixa etaria.',
    supportText: 'Planejamento semanal',
  },
  {
    id: 'eja',
    label: 'EJA',
    icon: GraduationCap,
    colorClass: 'text-indigo-600',
    description: 'Matriculas, concluintes e evolucao da Educacao de Jovens e Adultos.',
    supportText: 'Jovens e adultos',
  },
  {
    id: 'ensino',
    label: 'Ensino',
    icon: BookOpen,
    colorClass: 'text-cyan-600',
    description: 'Desempenho, frequencia, aprovacao e fluxo escolar.',
    supportText: 'Fluxo escolar',
  },
  {
    id: 'fundeb',
    label: 'FUNDEB',
    icon: DollarSign,
    colorClass: 'text-amber-600',
    description: 'Receitas, despesas e aplicacao dos recursos educacionais.',
    supportText: 'Receitas e despesas',
  },
  {
    id: 'ideb',
    label: 'IDEB',
    icon: TrendingUp,
    colorClass: 'text-blue-600',
    description: 'Evolucao das notas, metas e comparativos por escola.',
    supportText: 'Metas e comparativos',
  },
  {
    id: 'licitacoes',
    label: 'Licitacoes',
    icon: FileText,
    colorClass: 'text-slate-600',
    description: 'Processos, modalidades, valores e situacao dos certames.',
    supportText: 'Processos e valores',
  },
  {
    id: 'matriculas',
    label: 'Matriculas',
    icon: UserPlus,
    colorClass: 'text-green-600',
    description: 'Quantidade de estudantes por modalidade, escola e zona.',
    supportText: 'Por modalidade',
  },
  {
    id: 'transporte',
    label: 'Transporte Escolar',
    icon: Bus,
    colorClass: 'text-purple-600',
    description: 'Rotas, alunos atendidos, veiculos e quilometragem.',
    supportText: 'Rotas e alunos',
  },
]
